(fset 'yes-or-no-p 'y-or-n-p)
(load-theme 'wombat)
(column-number-mode)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(prefer-coding-system 'utf-8)
(setq inhibit-splash-screen t)
(setq visible-bell t)
